
class ArgumentError(Exception):

    pass

class ArgumentRangeError(Exception):

    pass